apiVersion: v1
kind: Service
metadata:
  name: echo-service
  annotations:
    # Note that the backend talks over HTTP.
    #service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    # TODO: Fill in with the ARN of your certificate.
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:eks:us-west-2:006587054012:cluster/terraform-eks-demo
    # Only run SSL on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  selector:
    app: echo-pod
  ports:
  - name: https
    port: 443
    targetPort: 80
  type: LoadBalancer


  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: echo-deployment
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: echo-pod
    template:
      metadata:
        labels:
          app: echo-pod
      spec:
        containers:
        - name: echoheaders
          image: k8s.gcr.io/echoserver:1.10
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
